trigger:
- master
pr:
- master
pool:
  vmImage: ubuntu-latest
container: mcr.microsoft.com/dotnet/core/sdk:3.0
steps:
- script: dotnet --version
  displayName: Check version of .NET container
- script: dotnet test
  displayName: Test .NET application
  workingDirectory: ./app.tests/
- script: dotnet publish --configuration Release --output out/win --self-contained --runtime win-x64 /p:PublishSingleFile=true /p:IncludeSymbolsInSingleFile=true
  displayName: Publish .NET application for Windows
  workingDirectory: ./app/
  condition: and(always(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  
