trigger:
- master
pr:
- master
pool:
  vmImage: ubuntu-latest
container: mcr.microsoft.com/dotnet/core/sdk:3.0
steps:
- script: dotnet --version
  displayName: Check version of .NET container
- script: dotnet test
  displayName: Test .NET application
  workingDirectory: ./app.tests/
- script: dotnet run
  displayName: Run .NET application
  workingDirectory: ./app/
- script: dotnet publish --configuration Release --output out/win-x64 --self-contained --runtime win-x64 /p:PublishSingleFile=true /p:IncludeSymbolsInSingleFile=true
  displayName: Publish .NET application for Windows
  workingDirectory: ./app/
- script: dotnet publish --configuration Release --output out/linux-x64 --self-contained --runtime linux-x64 /p:PublishSingleFile=true /p:IncludeSymbolsInSingleFile=true
  displayName: Publish .NET application for Linux
  workingDirectory: ./app/
- script: dotnet publish --configuration Release --output out/osx-x64 --self-contained --runtime osx-x64 /p:PublishSingleFile=true /p:IncludeSymbolsInSingleFile=true
  displayName: Publish .NET application for MacOS
  workingDirectory: ./app/
- task: PublishBuildArtifacts@1
  displayName: Publish my build artifacts
  pathToPublish: app/out
  artifactName: distributions
  
